### ISSUE TITLE
About XLIR

### ISSUE THREAD

**Issue by ibeidu** [CGCL-codes/naturalcc#18]
Hello, dear authors, Naturalcc is an excellent work.
I read the paper "Cross-Language Binary-Source Code Matching with Intermediate Representations" and interested in the approach of embedding of IR Bitcode. 
Unfortunately, I didn't find available code or apporach of XLIR. Could you give me some help to find the location of this work?

Look forward to your favourable reply.

**Comment by gystar** [comment]
Sorry, we will release the code later.
For embedding IR,  we followed the work of OSCAR.
Maybe you can refer [this](https://github.com/pdlan/OSCAR).

**Comment by BlackBird-BB** [comment]
I have read the work of XLIR. I think It's a great work on BSCM. But I didn't find available code or apporach of XLIR. Maybe I missed something. Could you please give me some help to find the location of this work?
