### ISSUE TITLE
missing code?

### ISSUE THREAD

**Issue by ibrahimabdelaziz** [CGCL-codes/naturalcc#2]
Hi,
The code keeps crashing with this error:
```
...
    from ncc.data.contracode.contracode_dataset import ContraCodeDataset
ModuleNotFoundError: No module named 'ncc.data.contracode'
```

By inspecting the folder ncc/data/, it seems `contracode` is missing. Please advise.

**Comment by whatsmyname** [comment]
Thank you for the feedback. We have fixed this ImportError bug by removing code lines.

More datasets and baselines will be released recently.
