### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/ncc_data/codesearchnet/raw/code.json'

### ISSUE THREAD

**Issue by SoWhereAreYou** [CGCL-codes/naturalcc#20]
Hello，dear author，I'm a chinese students in WuHan.
I'm sorry I am confused about it.I can not use geogle drive. So I download it by myself.Could you tell me how to use geogle drive in Lab...oh my god.
And I excute python -m dataset.python_wan.attributes_cast it tell me error as up.
It said FileNotFoundError: [Errno 2] No such file or directory: '/data/ncc_data/codesearchnet/raw/code.json'.How can I run it? Please help me thank you.

**Comment by whatsmyname** [comment]
1) open the link (https://github.com/CGCL-codes/naturalcc/blob/a7561505375ca298d9d5578586240bed27a9a674/ncc_dataset/python_wan/download.sh#L10), 
2) download it with your explorer and unzip and move it to /data/ncc_data/codesearchnet/raw/

**Comment by SoWhereAreYou** [comment]
> 1. open the link (https://github.com/CGCL-codes/naturalcc/blob/a7561505375ca298d9d5578586240bed27a9a674/ncc_dataset/python_wan/download.sh#L10
>    ),
> 2. download it with your explorer and unzip and move it to /data/ncc_data/codesearchnet/raw/
Thank you for your fast and efficiency reply，however here is another strange problem.You see here said FileNotFoundError: [Errno 2] No such file or directory: '/data/ncc_data/codesearchnet/raw/valid/code.original' does the vaild hais been spelled wrong？I has the “vaild” dir

**Comment by SoWhereAreYou** [comment]
> 1. open the link (https://github.com/CGCL-codes/naturalcc/blob/a7561505375ca298d9d5578586240bed27a9a674/ncc_dataset/python_wan/download.sh#L10
>    ),
> 2. download it with your explorer and unzip and move it to /data/ncc_data/codesearchnet/raw/

Sorry and I see another problem and it seem in pre issue.Has it been done now?
ModuleNotFoundError: No module named 'dataset.augmented_javascript'

**Comment by SoWhereAreYou** [comment]
> 1. open the link (https://github.com/CGCL-codes/naturalcc/blob/a7561505375ca298d9d5578586240bed27a9a674/ncc_dataset/python_wan/download.sh#L10
>    ),
> 2. download it with your explorer and unzip and move it to /data/ncc_data/codesearchnet/raw/

Hello，I have solve the problems before,but how could I solve it?It seems a os Errors and the ncc_data dir is dispute?Could I config it?
OSError: Model file not found: /data/ncc_data/ncc_data/python_wan/summarization/data-mmap/transformer/checkpoints/checkpoint_best.pt

**Comment by whatsmyname** [comment]
This OSError is caused by the NaturalCC cannot find your trained model file (checkpoint_best.pt) for evaluation or inference.
All shell scripts have been tested to be correct. Your errors might result from the internet connection, e.g., cannot run download.sh. 
So please try to understand the shell scripts and run commands manually if you cannot follow the instructions successfully.

**Comment by SoWhereAreYou** [comment]
> This OSError is caused by the NaturalCC cannot find your trained model file (checkpoint_best.pt) for evaluation or inference. All shell scripts have been tested to be correct. Your errors might result from the internet connection, e.g., cannot run download.sh. So please try to understand the shell scripts and run commands manually if you cannot follow the instructions successfully.

Oh，thank you,I wil try it in lab tommorrw.And I'm sorry I have so many problem and trouble you.But I must try to solve it.Do you know the paper "Cross-Language Binary-Source Code Matching with Intermediate Representations"？The author said the code will be available on ncc？

**Comment by whatsmyname** [comment]
@wanyao1992 
I think he can respond to your question.

**Comment by SoWhereAreYou** [comment]
> @wanyao1992 I think he can respond to your question.
Wow！You hust really cool! I just want to follow your rearsch.Sorry if I be more carefully I would find it early.
