### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by SoWhereAreYou** [CGCL-codes/naturalcc#24]
Hi,
Thank you before and i find how to train.
But the when I have trained a epoch.It will out of memory afte any set in max_sentences: 1
Was it has not fresh the gpu after ever epoch?
![image](https://user-images.githubusercontent.com/30107831/201921652-6190df9e-1ae6-419b-8381-dd9511f4df2c.png)
Looking for your reply.
Thanks.

**Comment by whatsmyname** [comment]
We do clear the GPU cache after an epoch.
Please, decrease your validation/eval batch size and try it again.

**Comment by SoWhereAreYou** [comment]
> 

Thanks for your advice.And i'm sorry for my ignorance. Could you share the memory size of used GPUs and the training time you took?

**Comment by whatsmyname** [comment]
Hope this may help you.
https://github.com/CGCL-codes/naturalcc/blob/master/run/summarization/neural_transformer/relative/python_wan/python.log

We have many training logs for neural models. Please, check them in the `run` directory.

**Comment by SoWhereAreYou** [comment]
> Hope this may help you. https://github.com/CGCL-codes/naturalcc/blob/master/run/summarization/neural_transformer/relative/python_wan/python.log
> 
> We have many training logs for neural models. Please, check them in the `run` directory.

I" had read it before.But thank you.
